// Component exports for better module resolution
export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Services } from './Services'
export { default as About } from './About'
export { default as Testimonials } from './Testimonials'
export { default as FAQ } from './FAQ'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
export { default as LazyAnimations } from './LazyAnimations' 